version: "3.5"

services:
  frontend:
    container_name: ${APP_NAME}-vue-standalone
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        user: is
        uid: 1000
    ports:
      - 2999:80
    volumes:
      - ./:/app
    networks:
      - ${APP_NAME}-network
networks:
  base-node-network:
    name: ${APP_NAME}-network
