version: "3.5"

services:
  backend:
    container_name: ${APP_NAME}-backend
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        user: is
        uid: 1000
    ports:
      - 3002:80
    volumes:
      - ./:/app
    networks:
      - ${APP_NAME}-network
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${APP_NAME}
    ports:
      - "3003:5432"
    networks:
      - ${APP_NAME}-network
networks:
  base-node-network:
    name: ${APP_NAME}-network
