version: '3.5'

services:
  frontend:
    container_name: ${APP_NAME}-frontend
    build:
      dockerfile: docker/Dockerfile
      args:
        user: rodrigo
        uid: 1000
    ports:
      - 3004:5173 #front
      - 3005:8000 #back
    volumes:
      - ./:/var/www/html
    networks:
      - base-node-network
networks:
  base-node-network:
    name: base-node-network